### ISSUE TITLE
install-wp: Permission denied

### ISSUE THREAD

**Issue by oxismailxo** [cosimoscarcella/wordpress-installer#2]
Hello Cosimo,

i pulled your project & run it but i'm getting this error when running ./wp-init.sh

the error:
![image](https://user-images.githubusercontent.com/68305651/143595846-914b42f5-3727-4358-8cea-621b26008aa9.png)

Thank you !

**Comment by cosimoscarcella** [comment]
Hi @oxismailxo,
thanks for noticing the issue. Let me know if this solves your problem.

Regards, Cosimo

**Comment by oxismailxo** [comment]
@cosimoscarcella ,

Thank you for time & fixing the problem, just another error showed up:
Warning: Failed to create directory '/etc/X11/fs/.wp-cli/cache/': mkdir(): Permission denied.

![image](https://user-images.githubusercontent.com/68305651/144729119-6874af52-2b7e-4227-ba6e-e9ae201f3267.png)

Thank you again !

**Comment by oxismailxo** [comment]
Hello Again @cosimoscarcella ,

I did some research and found there is a difference between wp-cli image user's UID & wp-cli image user's UID cause wp-cli is alpine: https://github.com/docker-library/wordpress/issues/417#issuecomment-514358315

So i added this variable "WP_CLI_CACHE_DIR: /tmp" to the wp-cli's environment:
  wp-cli:
    depends_on:
      - mysql
      - wordpress
    image: wordpress:cli
    env_file: .env
    user: xfs
    environment:
      WP_CLI_CACHE_DIR: /tmp
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
 
Thank you @cosimoscarcella  for this great project !
